* =ploterific=

=ploterific= is a command line program meant for a quick and easy way to plot
tabular data from the command line. Meant for quick visualizations, not too
customizable.

** Installation

#+begin_src bash
git clone https://github.com/GregorySchwartz/ploterific.git
cd ploterific
nix-env -f default.nix -i ploterific
#+end_src

** Usage

Based on some tabular data, for instance:

#+HEADER: :results file
#+HEADER: :exports both
#+begin_src bash
mkdir example
wget -O iris.csv "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
cat iris.csv | sed "1i sepalLength,sepalWidth,petalLength,petalWidth,class" | ploterific -f "sepalLength:Q" -f "sepalWidth:Q" -c "class:N" -m Circle > example/out.html
printf ./example/out.html
#+end_src

[[file:./example/out.html]]

Here, each =-f= denotes the axes in order, with =:Q= signifying they are
quantitative data (=N=, =O=, =Q=, or =T= for nominal, ordinal, quantitiative, or
temporal measurements, respectively). The data is colored by =-c=, nominal data,
with a =Circle= mark (lists of marks availabel at
https://hackage.haskell.org/package/hvega-0.11.0.1/docs/Graphics-Vega-VegaLite.html#t:Mark).
For additional information, see =ploterific -h=.

*Importantly*, any observations with feature numbers that cannot be parsed will
be thrown out automatically! Also note, if there is any kind of non-Haskell
issue (seen by =cat out.html=), then it is probably due to =vega-lite= (for
instance, having periods in column names will not work), so check =vega-lite='s
documentation first.

 
